In [9]:
import numpy as np

In [10]:
# storing a state
state = np.array([1,2,3,8,6,4,7,5,0]).reshape(3,3)

print(state)

[[1 2 3]
 [8 6 4]
 [7 5 0]]


In [1]:
import numpy as np
c_state = np.array([1,2,3,8,6,4,7,5,0]).reshape(3,3)
print(c_state)

[[1 2 3]
 [8 6 4]
 [7 5 0]]


In [12]:
# getting location of empty tile i.e. zero

zero_location = [x[0] for x in np.where(state==0)] 
zero_location

[2, 2]

In [13]:
# creating copy of state

copy = state.copy()
copy

array([[1, 2, 3],
       [8, 6, 4],
       [7, 5, 0]])

In [14]:
# generating new state by swaping value in feasible direction

swap_value = state[zero_location[0],zero_location[1]-1] 
print(swap_value)

copy[zero_location[0],zero_location[1]-1] = 0
copy[zero_location[0],zero_location[1]] = swap_value
print(copy)

5
[[1 2 3]
 [8 6 4]
 [7 0 5]]


In [3]:
# calculating mismatched tiles
import numpy as np
state = np.array([1,2,3,8,6,4,7,5,0]).reshape(3,3)
c_state = np.array([1,3,2,8,6,4,7,5,0]).reshape(3,3)
cost = np.sum(state != c_state)
print(cost)

2


In [16]:
# detecting goal state
print(np.array_equal(copy,state))
print(np.array_equal(c_state,state))


False
False
